### ISSUE TITLE
Can Kubernetes Helm include a link to this?

### ISSUE THREAD

**Issue by technosophos** [sapcc/openstack-helm#1]
Hey, we'd really like to add a link to our docs to use this as an example of a sophisticated multi-service chart. You all have come up with some clever ways of configuring what is in my mind one of the most complex open source tools out there (I used to work on it at HP Cloud).

I know this project is brand new, so I wanted to explicitly ask your permission before doing so.

**Comment by BugRoger** [comment]
Permission granted. Link away!

**Comment by BugRoger** [comment]
We also wouldn't mind seeing this as a reference implementation in the kubernetes or kubernetes-incubator organization. Though we are still iterating on this and might have to do significant changes... A bit too early still.

**Comment by technosophos** [comment]
Fabulous! @prydonius and @viglesiasce are the maintainers of that repo. I'll tag them and ya'll can follow up.

I've added a PR pointing here. https://github.com/kubernetes/helm/pull/1481/files

EDIT: fixed Vic's github handle.
