### ISSUE TITLE
i want install openstack and elektra

### ISSUE THREAD

**Issue by rmros** [sapcc/openstack-helm#109]
i want launch elektra ui 
so before that i need install openstack helm "https://github.com/sapcc/openstack-helm"

but i cant find any document material about install openstack with yours openstack helm repo
how i can?

**Comment by edda** [comment]
That repo contains all of our helm-charts. It's how we install OpenStack. You don't need to do it like that, it only makes sense to look into this if you also want to run your OpenStack on kubernetes. If you just want to try out Elektra, the easiest way is to install DevStack.
