### ISSUE TITLE
whats diffrent between sapcc helm chart and sapcc openstack helm,

### ISSUE THREAD

**Issue by rmros** [sapcc/openstack-helm#110]
whats diffrent between sapcc helm chart and sapcc openstack helm,
i know what is openstack helm but i dont know what have addition helm chart?

**Comment by vonneudeck** [comment]
`openstack-helm` is for running Openstack with Helm on Kubernetes.
`helm-charts` contains Helm charts required by the SAP Converge Cloud. You don’t need them.
