### ISSUE TITLE
elektra Extended services

### ISSUE THREAD

**Issue by rmros** [sapcc/openstack-helm#111]
i read elektra readme , 
its said have these features:
Extended services:
SAP Automation as a Service
SAP Hana as a Service
SAP Kubernetes as a Service

is it work for me after install elektara ?  or its private repository ? how i can access to that?

**Comment by notque** [comment]
Elektra supports those components from a ui perspective. We also have repos for the actual components. 

I do not believe we have any end to end documentation on getting all of that running. Someone will correct me if I'm wrong.

**Comment by rmros** [comment]
@notque so i want see this actual components, please show me way
