### ISSUE TITLE
make registry configurable via private values

### ISSUE THREAD

**Issue by urfuwo** [sapcc/openstack-helm#19]
remove references to sapcc registry and replace with private value configuration
https://github.com/sapcc/openstack-helm/blob/8a1f9bc49e04549ab409c3ebd807060b608e75b5/postgres/templates/deployment.yaml#L47

**Comment by abattye** [comment]
Fixed in https://github.com/sapcc/openstack-helm/commit/6e0895f8cda839765a31345c19548159719afce1
